### ISSUE TITLE
ERROR_ACCESS on Windows

### ISSUE THREAD

**Issue by avantgardnerio** [Huddly/sdk#210]
When trying to run the 

```Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\bgardner\workspace\huddly-test> node --version
v8.11.2
PS C:\Users\bgardner\workspace\huddly-test> node .\index.js
(node:13988) Warning: N-API is an experimental feature and could change at any time.
2019-10-9 | 18:31:46:574 | DEBUG | Device API USB Manager | Got ATTACH event from device with id 10003
    at Object.errstr (C:\Users\bgardner\workspace\huddly-test\node_modules\@huddly\device-api-usb\src\errstr.ts:10:14)
    at _cpp.openDevice.handle (C:\Users\bgardner\workspace\huddly-test\node_modules\@huddly\device-api-usb\src\bulkusbdevice.ts:42:31)
2019-10-9 | 18:31:47:906 | WARN | SDK DeviceFactory | Transport init on main device api failed. Falling back to secondary device apis
2019-10-9 | 18:31:48:175 | DEBUG | Device API USB Manager | DeviceList found 1 enumerated Huddly devices
2019-10-9 | 18:31:48:176 | DEBUG | Device API USB Manager | Filtering the devices for the following serial number: LIBUSB_ERROR_ACCESS
Libusb: libusb_open failed: LIBUSB_ERROR_ACCESS
Opening device failed: LIBUSB_ERROR_ACCESS. Retrying.
Libusb: libusb_open failed: LIBUSB_ERROR_ACCESS
Opening device failed: LIBUSB_ERROR_ACCESS. Retrying.
Libusb: libusb_open failed: LIBUSB_ERROR_ACCESS
2019-10-9 | 18:31:49:202 | ERROR | Device API USB Transport | Unable to open device / claim endpoint
Error: LIBUSB_ERROR_ACCESS
    at Object.errstr (C:\Users\bgardner\workspace\huddly-test\node_modules\@huddly\device-api-usb\src\errstr.ts:10:14)
    at _cpp.openDevice.handle (C:\Users\bgardner\workspace\huddly-test\node_modules\@huddly\device-api-usb\src\bulkusbdevice.ts:42:31)
2019-10-9 | 18:31:49:212 | ERROR | Device API USB | HLink is not supported for device: LIBUSB_ERROR_ACCESS
Error: LIBUSB_ERROR_ACCESS
    at Object.errstr (C:\Users\bgardner\workspace\huddly-test\node_modules\@huddly\device-api-usb\src\errstr.ts:10:14)
    at _cpp.openDevice.handle (C:\Users\bgardner\workspace\huddly-test\node_modules\@huddly\device-api-usb\src\bulkusbdevice.ts:42:31)
2019-10-9 | 18:31:49:215 | ERROR | Generic Component | Could not get device Error: Unable to find appropriate transport implementation for device: {"_cpp":{},"vid":11225,"pid":33,"serialNumber":"LIBUSB_ERROR_ACCESS","location":[1,2],"_cookie":10003,"_onDetaches":[null],"id":10003,"productId":33}
SDK
```

This is my package.json:

```
{
  "name": "huddly-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@huddly/device-api-usb": "^0.2.9",
    "@huddly/sdk": "^0.3.1"
  }
}
```

I had to modify the demo app a bit: 

```const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlySdk = require('@huddly/sdk').default;

const meetingRoomName = process.env.HUDDLY_MEETING_ROOM || 'TEST_ROOM';

const usbApi = new HuddlyDeviceAPIUSB();

// Create an instance of the SDK
const sdk = new HuddlySdk(usbApi, [usbApi]);

async function init() {
  await sdk.init();

  sdk.on('ATTACH', async (cameraManager) => {
    const detector = await cameraManager.getDetector();
    await detector.init();

    detector.on('DETECTIONS', detections => {
      console.log(meetingRoomName, detections.length);
    });

    detector.start();
  });
}

init();
```

vs the one from the README:

```    
const autozoomCtl = cameraManager.getAutozoomControl();
    // Make sure that autozoom (genius framing is started)
    await autozoomCtl.init();
    await autozoomCtl.start();

    // Now get the detector instance from sdk
    const detector = cameraManager.getDetector();
```

Due to a change in the library. This is using the Huddly app 2.0.49. I've tried with and without an open camera preview session. My node version is `v8.11.2`. I'd appreciate any help I can get, thanks!

**Comment by brikendr** [comment]
Hei @avantgardnerio 

According to what your error log says, it seems that when you are running the sample script, the camera is already occupied by a different application or process and as a result you get a `LIBUSB_ERROR_ACCESS` error. You need to make sure that you are not running the Huddly App while you are trying to test the sample script. 

Huddly App also uses the sdk which means that it will occupy the interface the SDK uses to communicate with the camera. Our sdk supports one and only one application at a time.

As for the documentation changes, we just have introduced a new feature where you are able to retrieve detection data without having to stream on the host machine. This new feature has not been released yet (latest release of sdk is still 0.3.1) but the documentation gets updated alongside with master branch. So in your case you need to use the old way (which you are) of retrieving detection data until the new sdk version is out together with camera firmware that supports the feature mentioned.

Please let us know if you get it to work.

**Comment by avantgardnerio** [comment]
I tried in ubuntu, which is my day-to-day OS, and I get no dections: 
```
bgardner@MERENG111L:~/workspace/hudly-sdk/examples/ga_peoplecount$ node ga_peoplecount.js 
2019-10-11 | 11:40:35:577 | DEBUG | Device API USB Manager | Got ATTACH event from device with id 10008
2019-10-11 | 11:40:35:828 | DEBUG | Device API USB Manager | DeviceList found 1 enumerated Huddly devices
2019-10-11 | 11:40:35:828 | DEBUG | Device API USB Manager | Filtering the devices for the following serial number: B41C00390
2019-10-11 | 11:40:35:835 | INFO | Device API USB | Transport Protocol is Hlink
2019-10-11 | 11:40:35:836 | WARN | SDK DeviceFactory | Preferred device api does not support uvc control interface
2019-10-11 | 11:40:35:838 | ERROR | SDK DeviceFactory | None of the device api's support uvc control interface

2019-10-11 | 11:40:35:843 | WARN | Generic Component | Uploading new framing config!
2019-10-11 | 11:40:36:53 | WARN | Generic Component | Start cnn enable
^C
bgardner@MERENG111L:~/workspace/hudly-sdk/examples/ga_peoplecount$ git branch
* master
bgardner@MERENG111L:~/workspace/hudly-sdk/examples/ga_peoplecount$ git remote -v
origin  https://github.com/Huddly/sdk.git (fetch)
origin  https://github.com/Huddly/sdk.git (push)
bgardner@MERENG111L:~/workspace/hudly-sdk/examples/ga_peoplecount$ cat package.json 
{
  "name": "ga_peoplecount",
  "version": "1.0.0",
  "description": "",
  "main": "ga_peoplecount.js",
  "scripts": {
    "start": "node ga_peoplecount.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@huddly/device-api-usb": "~0.2",
    "@huddly/sdk": "~0.2",
    "got": "~9.2.2"
  }
}
bgardner@MERENG111L:~/workspace/hudly-sdk/examples/ga_peoplecount$ 
```

I updated the example to log instead of track:
```
    detector.on('DETECTIONS', detections => {
      console.log(`${detections.length} people detected`)
    });
```

master is on 0.2. I can try 0.3.1 next.

**Comment by avantgardnerio** [comment]
When I bump to 0.3, I get this: 

```
bgardner@MERENG111L:~/workspace/hudly-sdk/examples/ga_peoplecount$ npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @huddly/device-api-usb@~0.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'ga_peoplecount'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bgardner/.npm/_logs/2019-10-11T17_45_34_168Z-debug.log
bgardner@MERENG111L:~/workspace/hudly-sdk/examples/ga_peoplecount$ 
```

I really appreciate your help!

**Comment by avantgardnerio** [comment]
Ah, got it, thanks!

I just had to have something streaming the video.

```
2019-10-11 | 11:55:51:953 | WARN | Generic Component | Start cnn enable
4 people detected
4 people detected
4 people detected
5 people detected
4 people detected
5 people detected
7 people detected
6 people detected
5 people detected
6 people detected
```

**Comment by jontore** [comment]
Great, just open another issue if you need help with something else.
