### ISSUE TITLE
Error when calling cameraManager.getAutozoomControl()

### ISSUE THREAD

**Issue by audunf** [Huddly/sdk#506]
Hi, 
I'm getting an error when I try to do: cameraManager.getAutozoomControl();

Ubuntu 21.10
node v14.17.3
```
  "dependencies": {
    "@huddly/device-api-ip": "^0.1.4",
    "@huddly/device-api-usb": "^0.3.2",
    "@huddly/sdk": "^0.6.3"
  }
```

Code:
```
const HuddlyDeviceAPIUSB = require('@huddly/device-api-usb').default;
const HuddlyDeviceApiIP = require('@huddly/device-api-ip').default;
const HuddlySdk = require('@huddly/sdk').default;

const usbApi = new HuddlyDeviceAPIUSB();
const ipApi = new HuddlyDeviceApiIP();

const sdk = new HuddlySdk(usbApi);

const Config = {
    cameraManager: false,
    autozoomCtrl: false,
    connected: false,
}

// Create a instance that will represent the `IDeviceManager` interface
sdk.on('ATTACH', (newDevice) => {
    Config.cameraManager = newDevice;
    Config.cameraManager.getInfo().then(console.log);
    if (Config.cameraManager.productName === "Huddly ONE") {
        console.log(`Huddly ONE connected`)
        Config.connected = true;
        console.log(`getAutozoomControl`)
        Config.autozoomCtrl = Config.cameraManager.getAutozoomControl();
        console.log(`getAutozoomControl done`)
        if (Config.autozoomCtrl) {
            console.log(`getAutozoomControl success - calling autozoomControl init`);
            Config.autozoomCtrl.init().then(_ => {
                console.log(`autozoomCtrl init done`);
            });
        } else {
            console.log(`getAutozoomControl failed`);
        }
    }
});

sdk.init();
```

Results in: 

```
~/src/huddly$ npm start
> NODE_ENV=production node src/index.js
Huddly ONE connected
getAutozoomControl
(node:19909) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'BulkUsbDevice'
    |     property '_openEndpoint' -> object with constructor 'BulkUsbEndpoint'
    --- property 'device' closes the circle
    at JSON.stringify (<anonymous>)
    at HuddlySdk.<anonymous> (/home/audunf/src/huddly/node_modules/@huddly/sdk/src/index.ts:227:92)
    at Generator.next (<anonymous>)
    at fulfilled (/home/audunf/src/huddly/node_modules/@huddly/sdk/lib/src/index.js:5:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19909) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either ....
{
  id: 10001,
  serialNumber: 'H40B00696',
  vendorId: 11225,
  productId: 81,
  version: '1.4.22-109426',
  location: [ 4, 1, 3 ],
  name: 'Huddly ONE',
  softwareVersion: 'HuddlyIQ-1.4.22-109426',
  uptime: 1095.65
}
```
Questions: 
1. Is it supposed to work on Linux? 
2. Am I doing the initialization sequence wrong, or is there a bug in the API?

**Comment by brikendr** [comment]
Hey @audunf,

The `getAutozoomControl` on the camera manager can potentially throw an exception (This should probably be documented and be more visible on the documentation site). So a strong recommendation is to wrap that with a try catch block. Doing so you would get a better error description of what is happening.

Now to answer your questions:
1. The sdk works on all operating systems (Win32, MacOS, Linux)
2. The initialization sequence is correct except for the `try..catch` block that a mentioned above that should be surrounding the `getAutozoomControl` command. The issue here is that your camera type (Huddly ONE) does not support the feature of getting the autozoom controls and interacting with this smart feature. Autozoom control are available on the following products:
   - [Huddly IQ](https://www.huddly.com/conference-cameras/iq/)
   - [Huddly L1](https://www.huddly.com/conference-cameras/l1/)

The Huddly ONE (which you are using in this example) does not include Genius Framing (Autozoom) in the [spec sheet](https://www.huddly.com/content/uploads/2021/10/Spec-sheet_ONE_WFAkit_121021.pdf)

**Comment by audunf** [comment]
Thanks! :)
